name: Deploy

on:
  push:
    branches:
      - src

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: install node and npm
        run: |
            sudo apt update
            sudo apt install nodejs npm
            node --version

      - name: start build script
        run: |
            npm install
            npm run build



      - name: Deploy to my github page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
