name: Building metis website

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: install node and npm
        run: |
            sudo apt update
            sudo apt install nodejs npm
            node --version

      - name: start build script
        run: |
            npm install
            npm run build




      - name: Push data to another repository
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist